# Generated by Django 6.0.4 on 2026-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='alcohol_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='exercise_intensity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='had_sex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='hair_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='physical_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='pill_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='sex_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='skin_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='stress_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='water_intake',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
