# Generated by Django 6.0.4 on 2026-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyentry_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_irregular_declared',
            field=models.BooleanField(default=False),
        ),
    ]
